### ISSUE TITLE
Initial Roadmap

### ISSUE THREAD

**Issue by mdbelt** [mdbelt/mongodb-cookbook#1]
***\* Development on "initial" branch. ****

Checklist to keep brain straight.
- [x] Generate initial cookbook with knife.
- [x] Sketch out basics.  Install with TAR.  Stand-up Service.
- [x] Open up iptables port for MongoDB
- [x] Replace hard-codes with attributes.
- [x] Consolidate structure into it's own cookbook.
- [x] Put directory in loop to consolidate code.
- [x] Get rid of warnings produced while using RHEL
- [x] README

Replicaset stuff:
- [x] Figure out syntax to communicate with mongo shell
- [x] Initialize RS block
- [x] Search for existing rs nodes using role search
- [x] Add new node to rs
- [x] Conditional Replset recipe.  Let's base it on name being specified as an attribute.

**Comment by mdbelt** [comment]
Moving test, log??, & distro?? to other topics.
